
# baseURL = '/'
languageCode = 'zh-CN'
languageDirection = 'ltr'
defaultContentLanguage = 'zh'
title = '非离坚白'
hasCJKLanguage=true
# theme= 'PaperMod'
summaryLength=30
removePathAccents = true
copyright= " © 2025 [非离坚白](https://aitioroyia.github.io/) Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).    Logo designed by  [rocketpixel / Freepik](http://www.freepik.com)"
mainSections = ['posts', 'courses']
[taxonomies]
  category = 'categories'
  tag = 'tags'
  author ='authors'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.highlight]
    linenos =true
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
    wrapperClass = 'highlight'


